In [1]:
import torch

In [3]:
token_embed = torch.ones((4,2,3))   # [batch_size, max_length, dim_vector]
print(token_embed)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [22]:
positional_embed = torch.randn((2,3,2))
print(positional_embed)
print(positional_embed[:,:2,:])

tensor([[[ 0.3238,  0.5934],
         [ 0.9412, -0.1174],
         [-0.3315, -1.1191]],

        [[-0.4827, -0.0314],
         [-0.0736, -0.8250],
         [-1.0358,  0.5460]]])
tensor([[[ 0.3238,  0.5934],
         [ 0.9412, -0.1174]],

        [[-0.4827, -0.0314],
         [-0.0736, -0.8250]]])


In [10]:
out = positional_embed + token_embed
print(out)

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]])
