In [1]:
import torch
a = torch.randn(3)
print(a)
print(a.long())

tensor([ 0.8730, -0.4496, -0.8085])
tensor([0, 0, 0])


In [10]:
import torch
a = torch.zeros(3,2)
print(a)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
a = torch.arange(0, 5)
aa =torch.randn(3,2)
b = aa.unsqueeze(1)
c = aa.unsqueeze(-2)
print(a.size())
print(b.size())
print(c.size())
print(c)

torch.Size([5])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])
tensor([[[ 5.0560e-01, -1.4414e+00]],

        [[ 9.3703e-04,  1.3117e+00]],

        [[-4.7362e-01, -3.7927e-01]]])


In [27]:
a1 = a.reshape(5,1)
print(a1)

tensor([[0],
        [1],
        [2],
        [3],
        [4]])


In [4]:
two_i = torch.arange(0,6,2,dtype=torch.float32)
print(two_i)

tensor([0., 2., 4.])
