In [1]:
import torch
a = torch.randn(3)
print(a)
print(a.long())

tensor([ 0.8730, -0.4496, -0.8085])
tensor([0, 0, 0])


In [2]:
'abc' > 'abbb'

True

In [10]:
import torch
a = torch.zeros(3,2)
print(a)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
a = torch.arange(0, 5)
aa =torch.randn(3,2)
b = aa.unsqueeze(1)
c = aa.unsqueeze(-2)
print(a.size())
print(b.size())
print(c.size())
print(c)

torch.Size([5])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])
tensor([[[ 5.0560e-01, -1.4414e+00]],

        [[ 9.3703e-04,  1.3117e+00]],

        [[-4.7362e-01, -3.7927e-01]]])


In [27]:
a1 = a.reshape(5,1)
print(a1)

tensor([[0],
        [1],
        [2],
        [3],
        [4]])


In [4]:
two_i = torch.arange(0,6,2,dtype=torch.float32)
print(two_i)

tensor([0., 2., 4.])


In [5]:
import torch

# 设置矩阵的形状（例如：3x4x5）
shape = (2, 4, 3)

# 生成随机整数矩阵
random_matrix = torch.randint(low=0, high=10, size=shape)

print(random_matrix)

tensor([[[7, 5, 4],
         [6, 7, 1],
         [8, 0, 8],
         [9, 3, 5]],

        [[9, 4, 0],
         [9, 7, 5],
         [1, 5, 2],
         [1, 5, 5]]])


In [10]:
addm = torch.ones((4,3))
print(addm)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
out = random_matrix + addm
print(out)

tensor([[[ 8.,  6.,  5.],
         [ 7.,  8.,  2.],
         [ 9.,  1.,  9.],
         [10.,  4.,  6.]],

        [[10.,  5.,  1.],
         [10.,  8.,  6.],
         [ 2.,  6.,  3.],
         [ 2.,  6.,  6.]]])


In [12]:
pos = torch.arange(0, 5)
print(pos)

tensor([0, 1, 2, 3, 4])


In [13]:
import torch
x = torch.tensor([[1, 2, 2],[2, 1, 3]])
x = x.transpose(0, 1)
print(x)

tensor([[1, 2],
        [2, 1],
        [2, 3]])


In [14]:
y = x.view(-1)
print(y)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [15]:
y = torch.reshape(x, [-1])
print(y)

tensor([1, 2, 2, 1, 2, 3])


In [19]:
x = torch.randint(1,10,(4,8,6))
print(x.size())
print(x)

torch.Size([4, 8, 6])
tensor([[[9, 4, 7, 2, 6, 4],
         [1, 5, 9, 6, 6, 5],
         [7, 9, 9, 9, 2, 2],
         [5, 4, 4, 6, 5, 3],
         [8, 1, 2, 5, 7, 1],
         [4, 3, 2, 6, 7, 1],
         [8, 2, 1, 2, 3, 6],
         [6, 3, 7, 1, 9, 3]],

        [[4, 2, 4, 6, 1, 5],
         [2, 8, 9, 4, 3, 7],
         [1, 8, 2, 1, 1, 5],
         [9, 1, 9, 2, 1, 9],
         [9, 7, 5, 2, 6, 1],
         [6, 3, 3, 5, 1, 5],
         [6, 1, 4, 3, 6, 4],
         [9, 3, 6, 7, 5, 8]],

        [[8, 3, 6, 4, 4, 6],
         [4, 5, 6, 8, 4, 7],
         [2, 6, 4, 8, 9, 8],
         [8, 3, 1, 5, 4, 2],
         [7, 9, 1, 9, 1, 5],
         [1, 9, 6, 8, 7, 7],
         [9, 2, 9, 6, 7, 9],
         [7, 6, 5, 9, 7, 2]],

        [[3, 5, 8, 5, 3, 8],
         [5, 8, 9, 2, 9, 4],
         [2, 2, 4, 3, 6, 2],
         [2, 3, 7, 4, 9, 6],
         [2, 6, 8, 7, 7, 7],
         [5, 8, 7, 6, 8, 1],
         [8, 8, 9, 2, 5, 9],
         [6, 8, 2, 2, 7, 1]]])


In [20]:
x1 = x.view(4,3,8,2)
print(x1)
x2 = x.view(4,8,3,2).transpose(1,2)
print(x2)

tensor([[[[9, 4],
          [7, 2],
          [6, 4],
          [1, 5],
          [9, 6],
          [6, 5],
          [7, 9],
          [9, 9]],

         [[2, 2],
          [5, 4],
          [4, 6],
          [5, 3],
          [8, 1],
          [2, 5],
          [7, 1],
          [4, 3]],

         [[2, 6],
          [7, 1],
          [8, 2],
          [1, 2],
          [3, 6],
          [6, 3],
          [7, 1],
          [9, 3]]],


        [[[4, 2],
          [4, 6],
          [1, 5],
          [2, 8],
          [9, 4],
          [3, 7],
          [1, 8],
          [2, 1]],

         [[1, 5],
          [9, 1],
          [9, 2],
          [1, 9],
          [9, 7],
          [5, 2],
          [6, 1],
          [6, 3]],

         [[3, 5],
          [1, 5],
          [6, 1],
          [4, 3],
          [6, 4],
          [9, 3],
          [6, 7],
          [5, 8]]],


        [[[8, 3],
          [6, 4],
          [4, 6],
          [4, 5],
          [6, 8],
          [4, 7],
          [2

In [22]:
print(x1)

tensor([[[[9, 4],
          [7, 2],
          [6, 4],
          [1, 5],
          [9, 6],
          [6, 5],
          [7, 9],
          [9, 9]],

         [[2, 2],
          [5, 4],
          [4, 6],
          [5, 3],
          [8, 1],
          [2, 5],
          [7, 1],
          [4, 3]],

         [[2, 6],
          [7, 1],
          [8, 2],
          [1, 2],
          [3, 6],
          [6, 3],
          [7, 1],
          [9, 3]]],


        [[[4, 2],
          [4, 6],
          [1, 5],
          [2, 8],
          [9, 4],
          [3, 7],
          [1, 8],
          [2, 1]],

         [[1, 5],
          [9, 1],
          [9, 2],
          [1, 9],
          [9, 7],
          [5, 2],
          [6, 1],
          [6, 3]],

         [[3, 5],
          [1, 5],
          [6, 1],
          [4, 3],
          [6, 4],
          [9, 3],
          [6, 7],
          [5, 8]]],


        [[[8, 3],
          [6, 4],
          [4, 6],
          [4, 5],
          [6, 8],
          [4, 7],
          [2

In [23]:
print(x2)

tensor([[[[9, 4],
          [1, 5],
          [7, 9],
          [5, 4],
          [8, 1],
          [4, 3],
          [8, 2],
          [6, 3]],

         [[7, 2],
          [9, 6],
          [9, 9],
          [4, 6],
          [2, 5],
          [2, 6],
          [1, 2],
          [7, 1]],

         [[6, 4],
          [6, 5],
          [2, 2],
          [5, 3],
          [7, 1],
          [7, 1],
          [3, 6],
          [9, 3]]],


        [[[4, 2],
          [2, 8],
          [1, 8],
          [9, 1],
          [9, 7],
          [6, 3],
          [6, 1],
          [9, 3]],

         [[4, 6],
          [9, 4],
          [2, 1],
          [9, 2],
          [5, 2],
          [3, 5],
          [4, 3],
          [6, 7]],

         [[1, 5],
          [3, 7],
          [1, 5],
          [1, 9],
          [6, 1],
          [1, 5],
          [6, 4],
          [5, 8]]],


        [[[8, 3],
          [4, 5],
          [2, 6],
          [8, 3],
          [7, 9],
          [1, 9],
          [9