In [9]:
import torch
a = torch.randn(3)
print(a)
print(a.long())

tensor([-1.1461, -1.0964,  0.9683])
tensor([-1, -1,  0])


In [10]:
import torch
a = torch.zeros(3,2)
print(a)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [13]:
a = torch.arange(0, 5)
b = torch.arange(0,5).unsqueeze(1)
print(a.size())
print(b.size())

torch.Size([5])
torch.Size([5, 1])


In [27]:
a1 = a.reshape(5,1)
print(a1)

tensor([[0],
        [1],
        [2],
        [3],
        [4]])
